CREATE TABLE `responses` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `age` int(1) NOT NULL,
  `sex` int(1) NOT NULL,
  `usage` int(1) NOT NULL,
  `response1` int(2) NOT NULL,
  `response2` int(2) NOT NULL,
  `response3` int(2) NOT NULL,
  `response4` int(2) NOT NULL,
  `response5` int(2) NOT NULL,
  `response6` int(2) NOT NULL,
  `response7` int(2) NOT NULL,
  `response8` int(2) NOT NULL,
  `response9` int(2) NOT NULL,
  `response10` int(2) NOT NULL,
  `response11` int(2) NOT NULL,
  `response12` int(2) NOT NULL,
  `response13` int(2) NOT NULL,
  `response14` int(2) NOT NULL,
  `response15` int(2) NOT NULL,
  `response16` int(2) NOT NULL,
  `response17` int(2) NOT NULL,
  `response18` int(2) NOT NULL,
  `response19` int(2) NOT NULL,
  `response20` int(2) NOT NULL,
  `response21` int(2) NOT NULL,
  `response22` int(2) NOT NULL,
  `response23` int(2) NOT NULL,
  `response24` int(2) NOT NULL,
  `response25` int(2) NOT NULL,
  `response26` int(2) NOT NULL,

  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;